apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-openldap-helm-chart.fullname" . }}
  labels:
    {{- include "simple-openldap-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ldap
      protocol: TCP
      name: ldap
  selector:
    {{- include "simple-openldap-helm-chart.selectorLabels" . | nindent 4 }}
